### ISSUE TITLE
XOR Gate in Risk Model?

### ISSUE THREAD

**Issue by DrMaxMK** [JoSQUANTUM/pygrnd#1]
When trying to replicate the sensitivity analysis I noticed that I don't know how to implement the XOR-Gate like in the arXiv paper.
Is there a way to run the notebook with exactly the risk model from the paper?

If I just ignore the XOR-Gate
  (via 
  nodes = ['0','1', "2", "3"]   # risk items defition
  edges=[('1','2'),('1','3')]  # correlations
  probsNodes={'0':0.8,'1':0.2,"2":0.1,"3":0.05}  # intrinsic probabilities
  probsEdges={('1','2'):0.5,('1','3'):0.4}  # transition probabilities)
the whole analysis gives no coherent answer. As visible here: ![image](https://user-images.githubusercontent.com/89843863/222101165-8f8c760e-ca66-4353-a43f-797af3385705.png)

When building it bottom up its not hard as you just implement the XOR with a CNOT-Gate (although I do not get the right answers there either) but is there a way to do it with the brm function?

**Comment by niklasjosq** [comment]
Hey DrMaxMK, thanks for your request - the XOR functionality is currently indeed not implemented in the brm.py in a general manner. In figure 2 of the paper "A Quantum Algorithm for the Sensitivity Analysis
of Business Risks" you can see a correct implementation of a circuit delivering correct results. If you have further questions we can setup a quick call. Your team from JoSQ
